### ISSUE TITLE
Md's Portfolio - No issues found

### ISSUE THREAD

**Issue by Masuduzzaman811** [Masuduzzaman811/Portfolio#10]
## Portfolio: accessibility
To check my portfolio page accessibility, I have checked all the items mentioned in the article [Easy Checks – A First Review of Web Accessibility](https://www.w3.org/WAI/test-evaluate/preliminary/)

I found no accessibility issues. The list below shows the items I have checked: 

- **Page title** - My page has a title.
- **Image text alternatives** - put `alt=" "` attribute to all `img` elements.
- **Text headings** - Put headings to all sections.
- **Color contrast** - Use dark text color on light background.
- **Resize** - Text and images can be resized by zooming on the page. The page layout is responsive too.
- **Interaction** - The page is accessible with a keyboard.
- **Moving content** - This page has no moving content.
- **Multimedia** - This page doesn't contain any multimedia files.
- **The basic structure of the page**

**Comment by ShoiraTa** [comment]
### **STATUS: APPROVED  ✔️** 
------
Hi @Masuduzzaman811,  

Your project is complete!  There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 


![giphy](https://user-images.githubusercontent.com/77038610/154916093-53a75ff8-ba21-44ad-a25e-bdea6200d8f1.gif)

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread by mentioning my Github username if something is not 100% clear.
***
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
