### ISSUE TITLE
Portfolio: application deploy

### ISSUE THREAD

**Issue by Masuduzzaman811** [Masuduzzaman811/Portfolio#8]
## Application deploy

This portfolio app has been deployed with the GitHub page. 

### Two previous issues and PR suggestions have been resolved:

- Added "Live Demo" with the project deployment link in README.md file
- Language category section alignment ( Inside "About-myself" section)
- "Get my resume" button top margin has been fixed

## Live Demo
[Masud's Portfolio](https://masuduzzaman811.github.io/Portfolio/)

**Comment by ShoiraTa** [comment]
### **STATUS: APPROVED  ✔️** 
------
Hi @Masuduzzaman811 ,  

Your project is complete! Congratulations!  🎉💯🌟 


![giphy](https://user-images.githubusercontent.com/77038610/154916093-53a75ff8-ba21-44ad-a25e-bdea6200d8f1.gif)

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread by mentioning my Github username if something is not 100% clear.
***
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
