### ISSUE TITLE
Section division

### ISSUE THREAD

**Issue by WillyStorm** [Masuduzzaman811/Portfolio#9]
https://github.com/Masuduzzaman811/Portfolio/blob/6c72a40365d4f19d7f853adb51dd77efa1c11c8b/index.html#L15

**Comment by WillyStorm** [comment]
Great job, on section division and commenting.Suggestions to remove any blank line.No need to keep empty lines while you using comments. Without it, the code will look way more clear. Keep up the good work.

**Comment by shahnawaza75** [comment]
Great job, on the layout it looks like the figma one just you can give little bit more border-radius. Keep up good work.👍
